export  const GET_ERRORS = 'GET_ERRORS'
export  const LOGIN ='LOGIN'
export  const REGISTER='REGISTER'
export  const SET_CURRENT_USER = 'SET_CURRENT_USER'
export  const FOLLOW = 'FOLLOW'
export  const UNFOLLOW = 'UNFOLLOW'